spring:
  application:
    name: logging-app

server:
  port: 8090
logging:
  level:
    pl.piomin.spring.logging.interceptor.SpringLoggingInterceptor: INFO
    pl.piomin.spring.logging.controller.ExampleController: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%4X{time}]) - %m%n"
